#pragma once

#include "frame_queue.hpp"
#include "sepia.hpp"

#include "parameters.h"
#include "track_update_queue.hpp"

#include <cstdint>
#include <memory>
#include <queue>
#include <string>
#include <vector>
#include <atomic>

#include <eigen3/Eigen/Dense>
#include <opencv2/core.hpp>

// Code generated by Claude AI for this set up.

class TrackManager;
class SAEdetector;
class TrackLogger;
class TrackSummaryLogger;
class DetectionCorroborationGrid;
class RawEventLogger;

namespace processing {
    //// ONE INSTANCE PER CAMERA ////

    class ProcessingPipeline {
    public:
        explicit ProcessingPipeline(uint8_t camera_id) : camera_id(camera_id) {}

        // ---- Processing thread ----
        //
        // Returns false if the config could not be loaded. Callers MUST check
        // this and not call process_batch() if it returns false - track_manager
        // and detector are left null in that case.
        bool setup(const std::string& config_name, frame_queue& frames, TrackUpdateQueue& threadC);
        
        // Called once per batch of events pulled off the camera queue, in
        // order, one batch at a time, on the same thread that called setup().
        // Feeds every event through the processing loop.
        void process_batch(const std::vector<sepia::dvs_event>& events);

        // Called once after the camera stops (on the same thread as setup()/
        // process_batch()). Releases the video writer and reports totals.
        void teardown();

        // ---- Render thread: all OpenCV GUI/video-writer calls live here ----
        //
        // These three must all run on the SAME thread as each other (a
        // dedicated render thread, separate from the one running setup()/
        // process_batch()/teardown() above) - and that thread must not be the
        // one running process_batch(), or you're back to blocking event
        // processing on frame rendering. render_setup() must not be called
        // until setup() (above) has already returned true, since it reads
        // config state (params/dispParams) setup() loaded.
    
        // Opens the display window and video writer (if configured), and
        // renders the initial empty frame - the render-thread equivalent of
        // what setup() used to do directly.
        void render_setup();
    
        // Draws and optionally saves/writes one frame from a self-contained
        // snapshot - never reads shared tracking state directly.
        bool render_frame(const frame_job& job);
    
        // Releases the video writer and destroys the window.
        void render_teardown();

        // -- Called from the camera's decode thread (handle_trigger_event) --
        //
        void on_trigger_event(int64_t raw_t_us, bool rising) {
            if (!rising) return; // only count each pulse once on its RISING edge
            pending_trigger_pulse_count.fetch_add(1, std::memory_order_relaxed);
            pending_internal_timestamp_of_last_trigger_pulse.store(raw_t_us, std::memory_order_release);
        }

    private:
        void high_pass(double ts, int x, int y, int p, int alpha);
        void high_pass_global(double ts, int& alpha);
        void publish_frame(double ts);
        void mru_touch(int slot);

        uint8_t camera_id;

        // ---- run configuration / state ----
        Parameters params;
        std::unique_ptr<TrackManager> track_manager;
        std::unique_ptr<SAEdetector> detector;
        std::unique_ptr<TrackLogger> track_logger;
        std::unique_ptr<TrackSummaryLogger> track_summary_logger;
        std::unique_ptr<DetectionCorroborationGrid> corroboration_grid;
        std::unique_ptr<RawEventLogger> raw_event_logger;

        frame_queue* frame_output = nullptr;
        TrackUpdateQueue* threadC_output = nullptr;

        // ---- trigger pulse handlers ----
        std::atomic<uint32_t> pending_trigger_pulse_count{0};
        std::atomic<int64_t> pending_internal_timestamp_of_last_trigger_pulse{-1};

        // worker thread equivalent variables
        uint64_t trigger_pulse_count = 0;
        double internal_timestamp_of_last_trigger_pulse = -1.0


        // ---- display / video output ----
        int image_count = 0;
        double t_next_publish = 0.0;

        // ---- reconstructed-image accumulators ----
        cv::Mat log_intensity_state, ts_array;
        double contrast_threshold = 0.0;
        // Buffer of events sharing a timestamp (cleared on track deletion).
        std::queue<std::pair<int, std::pair<int, int>>> same_ts_e_buffer;

        // ---- per-event bookkeeping ----
        uint64_t total_events = 0;
        bool have_first_ts = false;
        double t1 = 0.0;               // first event's raw sensor timestamp (µs), used as the zero point
        double t_last = -1.0;          // sentinel: -1.0 means "not yet set"
        double ts_kf_last = 0.0;
        double distance = 0.0;
        int id = 0;
        double detection_event_count = 0.0;
        int double_track_evaluation_counter = 0;
        int full_evaluation_counter = 0;
        Eigen::Vector3d e;              // event measurement, packed as (x, y, ts) each iteration

        std::vector<int> deleted_IDs_scratch;

        // distance thresholds cached in squared form once per batch-run so the per-event search never needs sqrt()/pow()
        double dist_threshold_sq = 0.0;
        double detector_dist_threshold_sq = 0.0;

        // ---- Kalman filter matrix templates ----
        // built once in setup() then handed to TrackManager (which makes its own per-track copies)
        Eigen::MatrixXd F, C, R, P, Q, A, x0;

        //detector type to use
        bool use_dt_detector = false;

        //whether or not to show the display
        bool show_display = true;

        // mru association cache for the most recently assigned tracks, for optimisation of nearest-neighbour association
        static constexpr int MRU_SIZE = 3;
        int mru_slots[MRU_SIZE];
        int mru_len = 0;
        uint64_t mru_hit_count = 0;
        uint64_t mru_miss_count = 0;
    };

} // namespace processing