// code generated by ClaudeAI for this set up

#pragma once
#include <algorithm>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <stdexcept>
#include <type_traits>

// ---------------------------------------------------------------------------
// Lock-free single-producer / single-consumer ring buffer.
//
//  * Exactly ONE producer thread (Thread C) and ONE consumer thread (writer).
//  * No locks, no syscalls, no allocation on the producer path.
//  * Producer and consumer indices live on separate cache lines, and each side
//    keeps a private cached copy of the other's index, so the shared atomics
//    are only touched when the cache says "full" (producer) or "empty"
//    (consumer) - in steady state the two threads barely communicate.
//  * Producer API is reserve / slot / commit: records are built IN PLACE in
//    the ring (no temp copies) and become visible to the consumer all at once
//    on commit, so a multi-record group (track start) is all-or-nothing.
//  * Consumer API is peek / pop: peek returns a pointer into the ring, so the
//    writer can write() straight from ring memory with no copy.
// ---------------------------------------------------------------------------
template <typename T>
class SpscRing {
    static_assert(std::is_trivially_copyable_v<T>, "ring elements must be trivially copyable");

public:
    struct Span { const T* ptr; size_t n; };

    explicit SpscRing(size_t capacity_pow2)
        : cap_(capacity_pow2), mask_(capacity_pow2 - 1) {
        if (capacity_pow2 < 2 || (capacity_pow2 & (capacity_pow2 - 1)) != 0)
            throw std::invalid_argument("SpscRing capacity must be a power of two >= 2");
        buf_.reset(new T[capacity_pow2]());   // value-init: zeroed, honours over-alignment (C++17)
    }

    size_t capacity() const { return cap_; }

    // ------------------------- producer side ------------------------------
    // Ensure n consecutive free slots exist. All-or-nothing.
    bool reserve(size_t n) noexcept {
        if (tail_local_ + n - head_cache_ > cap_) {
            head_cache_ = head_.load(std::memory_order_acquire);
            if (tail_local_ + n - head_cache_ > cap_) return false;
        }
        return true;
    }
    // i-th reserved slot (valid for i < n after a successful reserve(n)).
    T& slot(size_t i) noexcept { return buf_[(tail_local_ + i) & mask_]; }
    // Publish n slots to the consumer.
    void commit(size_t n) noexcept {
        tail_local_ += n;
        tail_.store(tail_local_, std::memory_order_release);
    }

    // ------------------------- consumer side ------------------------------
    // Largest contiguous run of unread elements (may be less than the total
    // available if the data wraps - call again after pop for the rest).
    Span peek() noexcept {
        if (tail_cache_ == head_local_) {
            tail_cache_ = tail_.load(std::memory_order_acquire);
            if (tail_cache_ == head_local_) return {nullptr, 0};
        }
        const size_t idx    = head_local_ & mask_;
        const size_t avail  = static_cast<size_t>(tail_cache_ - head_local_);
        return {&buf_[idx], std::min(avail, cap_ - idx)};
    }
    void pop(size_t n) noexcept {
        head_local_ += n;
        head_.store(head_local_, std::memory_order_release);
    }

private:
    const size_t cap_;
    const size_t mask_;
    std::unique_ptr<T[]> buf_;

    // Producer-owned cache line
    alignas(64) std::atomic<uint64_t> tail_{0};
    uint64_t tail_local_ = 0;
    uint64_t head_cache_ = 0;

    // Consumer-owned cache line
    alignas(64) std::atomic<uint64_t> head_{0};
    uint64_t head_local_ = 0;
    uint64_t tail_cache_ = 0;
};