// Code generated by Claude AI specifically for this set up

#pragma once
#include <opencv2/calib3d.hpp>
#include <opencv2/core.hpp>
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <vector>

struct LutEntry { float ux, uy, j00, j01, j10, j11; };

class UndistortLUT {
public:
    bool build(const std::array<double, 9>& K_arr, const std::array<double, 5>& D_arr, int W, int H) {
        if (W <= 2 || H <= 2) return false;
        W_ = W; H_ = H;
        const cv::Matx33d K(K_arr.data());
        const cv::Mat D = (cv::Mat_<double>(1, 5) << D_arr[0], D_arr[1], D_arr[2], D_arr[3], D_arr[4]);

        std::vector<cv::Point2d> grid(size_t(W) * H), und;
        for (int y = 0; y < H; ++y)
            for (int x = 0; x < W; ++x) grid[size_t(y) * W + x] = {double(x), double(y)};
        cv::undistortPoints(grid, und, K, D, cv::noArray(), K,
            cv::TermCriteria(cv::TermCriteria::COUNT | cv::TermCriteria::EPS, 100, 1e-12));

        lut_.assign(size_t(W) * H, LutEntry{});
        valid_.assign(size_t(W) * H, 0);

        const double fx = K(0,0), fy = K(1,1), cx = K(0,2), cy = K(1,2);
        auto distort = [&](const cv::Point2d& pu) {          // forward model, to verify the inverse
            const double x = (pu.x - cx) / fx, y = (pu.y - cy) / fy;
            const double r2 = x*x + y*y;
            const double rad = 1 + D_arr[0]*r2 + D_arr[1]*r2*r2 + D_arr[4]*r2*r2*r2;
            const double xd = x*rad + 2*D_arr[2]*x*y + D_arr[3]*(r2 + 2*x*x);
            const double yd = y*rad + D_arr[2]*(r2 + 2*y*y) + 2*D_arr[3]*x*y;
            return cv::Point2d(fx*xd + cx, fy*yd + cy);
        };

        size_t n_bad = 0;
        for (int y = 0; y < H; ++y) {
            const int ym = std::max(y - 1, 0), yp = std::min(y + 1, H - 1);
            for (int x = 0; x < W; ++x) {
                const int xm = std::max(x - 1, 0), xp = std::min(x + 1, W - 1);
                const size_t i = size_t(y) * W + x;
                const cv::Point2d& c = und[i];
                const cv::Point2d back = distort(c);
                const bool ok = std::isfinite(c.x) && std::isfinite(c.y) &&
                                std::hypot(back.x - x, back.y - y) < 0.05;   // inverse really inverts
                if (!ok) { ++n_bad; continue; }

                const cv::Point2d dxv = (und[size_t(y)*W + xp] - und[size_t(y)*W + xm]) * (1.0 / (xp - xm));
                const cv::Point2d dyv = (und[size_t(yp)*W + x] - und[size_t(ym)*W + x]) * (1.0 / (yp - ym));
                lut_[i] = { float(c.x), float(c.y),
                            float(dxv.x), float(dyv.x),      // j00 = dux/dx, j01 = dux/dy
                            float(dxv.y), float(dyv.y) };    // j10 = duy/dx, j11 = duy/dy
                valid_[i] = 1;
            }
        }
        std::cerr << "[UndistortLUT] " << W << "x" << H << ": " << n_bad << " of " << size_t(W) * H
                  << " pixels not invertible (will be rejected)\n";
        return true;
    }

    // In place: raw pixel state -> undistorted pixel state. False => drop this update.
    // Works for any state type with double-convertible x, y, vx, vy.
    template <class State>
    inline bool apply(State& s) const {
        const double sx = s.x, sy = s.y;
        if (!(sx >= 0.0 && sy >= 0.0 && sx < W_ - 1 && sy < H_ - 1)) return false;   // also rejects NaN
        const int x0 = int(sx), y0 = int(sy);
        const size_t i = size_t(y0) * W_ + x0;
        if (!(valid_[i] & valid_[i + 1] & valid_[i + W_] & valid_[i + W_ + 1])) return false;

        const LutEntry &e00 = lut_[i], &e10 = lut_[i + 1], &e01 = lut_[i + W_], &e11 = lut_[i + W_ + 1];
        const double fx = sx - x0, fy = sy - y0;
        const double w00 = (1 - fx) * (1 - fy), w10 = fx * (1 - fy), w01 = (1 - fx) * fy, w11 = fx * fy;
        const double ux = w00*e00.ux + w10*e10.ux + w01*e01.ux + w11*e11.ux;
        const double uy = w00*e00.uy + w10*e10.uy + w01*e01.uy + w11*e11.uy;

        const LutEntry& j = (fx < 0.5 ? (fy < 0.5 ? e00 : e01) : (fy < 0.5 ? e10 : e11));
        const double vx = double(j.j00) * s.vx + double(j.j01) * s.vy;
        const double vy = double(j.j10) * s.vx + double(j.j11) * s.vy;

        s.x = ux; s.y = uy; s.vx = vx; s.vy = vy;
        return true;
    }

private:
    int W_ = 0, H_ = 0;
    std::vector<LutEntry> lut_;
    std::vector<uint8_t> valid_;
};