// Writer for the stereo 3D track logs - from Thread C //
//  Thread C --push--> [SPSC ring of 64-byte records] --> writer thread --> file

// Code generated by Claude AI for this setup
#include "writer_queue.hpp"

#include <cerrno>
#include <chrono>
#include <cstring>
#include <iostream>

#include <fcntl.h>
#include <unistd.h>

namespace {
    constexpr uint64_t PREALLOC_CHUNK = 64ull << 20;                  // grow file 64 MiB at a time
    constexpr auto     IDLE_SLEEP     = std::chrono::milliseconds(2); // poll period when ring is empty
    constexpr auto     SYNC_INTERVAL  = std::chrono::seconds(1);      // fdatasync at most this often
}

bool WriterQueue::start(const std::string& path, size_t ring_capacity_records) {
    if (running_.load() || thread_.joinable()) return false;

    ring_ = std::make_unique<SpscRing<raemot3d_file::Record>>(ring_capacity_records);

    // NOTE: O_TRUNC - an existing file at `path` is overwritten. Ensure passed in file name is unique to avoid this
    fd_ = ::open(path.c_str(), O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0644);
    if (fd_ < 0) {
        std::cerr << "[Writer] cannot open " << path << ": " << std::strerror(errno) << "\n";
        ring_.reset();          // producer calls become counted drops instead of crashes
        return false;
    }

    raemot3d_file::FileHeader h{};
    std::memcpy(h.magic, raemot3d_file::MAGIC, sizeof(h.magic));
    h.version = raemot3d_file::VERSION;
    h.record_size = sizeof(raemot3d_file::Record);
    h.created_unix_ns = static_cast<uint64_t>(
        std::chrono::duration_cast<std::chrono::nanoseconds>(
            std::chrono::system_clock::now().time_since_epoch()).count());
    if (!write_bytes(&h, sizeof(h))) { ::close(fd_); fd_ = -1; ring_.reset(); return false; }

    running_.store(true, std::memory_order_release);
    thread_ = std::thread(&WriterQueue::run, this);
    return true;
}

void WriterQueue::stop() {
    if (!thread_.joinable()) return;
    running_.store(false, std::memory_order_release);   // producer's pushes happen-before this
    thread_.join();
}

// Blocking write of the whole buffer, with chunked preallocation ahead of it.
bool WriterQueue::write_bytes(const void* data, size_t len) {
    if (io_failed_.load(std::memory_order_relaxed)) return false;

    // Preallocate ahead of the write pointer so filesystem block allocation never
    // happens inside a write(). fallocate() (unlike posix_fallocate) fails fast on
    // filesystems that don't support it instead of emulating by writing zeros.
    while (prealloc_ok_ && bytes_total_ + len > allocated_) {
        if (::fallocate(fd_, 0, static_cast<off_t>(allocated_), static_cast<off_t>(PREALLOC_CHUNK)) == 0) {
            allocated_ += PREALLOC_CHUNK;
        } else {
            prealloc_ok_ = false;   // fall back to plain appends
        }
    }

    const char* p = static_cast<const char*>(data);
    while (len > 0) {
        const ssize_t n = ::write(fd_, p, len);
        if (n < 0) {
            if (errno == EINTR) continue;
            std::cerr << "[Writer] write failed: " << std::strerror(errno)
                      << " - further records will be discarded\n";
            io_failed_.store(true, std::memory_order_relaxed);
            return false;
        }
        p += n;
        len -= static_cast<size_t>(n);
        bytes_total_ += static_cast<uint64_t>(n);
    }
    dirty_ = true;
    return true;
}

void WriterQueue::run() {
    using clock = std::chrono::steady_clock;
    auto last_sync = clock::now();

    for (;;) {
        // Read the stop flag BEFORE looking at the ring: if it was already false,
        // every push made before stop() is visible to the peek below, so an empty
        // ring at that point really means "done".
        const bool stopping = !running_.load(std::memory_order_acquire);

        const auto span = ring_->peek();
        if (span.n > 0) {
            // Zero-copy: write straight out of ring memory. If the data wraps, the
            // next iteration picks up the second contiguous run immediately.
            if (write_bytes(span.ptr, span.n * sizeof(raemot3d_file::Record)))
                written_.fetch_add(span.n, std::memory_order_relaxed);
            ring_->pop(span.n);     // always consume, even on I/O failure, so producer never backs up
            continue;               // drain fully before sleeping
        }

        if (stopping) break;

        if (dirty_ && clock::now() - last_sync >= SYNC_INTERVAL) {
            ::fdatasync(fd_);
            dirty_ = false;
            last_sync = clock::now();
        }
        std::this_thread::sleep_for(IDLE_SLEEP);
    }

    // Finalise: trim preallocation back to the real size, flush, close.
    if (fd_ >= 0) {
        if (!io_failed_.load(std::memory_order_relaxed)) {
            if (::ftruncate(fd_, static_cast<off_t>(bytes_total_)) != 0)
                std::cerr << "[Writer] ftruncate failed: " << std::strerror(errno) << "\n";
            ::fdatasync(fd_);
        }
        ::close(fd_);
        fd_ = -1;
    }
}