// Writer for the stereo 3D track logs - from Thread C //
//  Thread C --push--> [SPSC ring of 64-byte records] --> writer thread --> file

// Code generated by Claude AI for this set up.
#pragma once
#include <atomic>
#include <cstdint>
#include <memory>
#include <string>
#include <thread>

#include "spsc_ring.hpp"
#include "raemot3d_file.hpp"
#include "track_types.hpp"   // State3D

class WriterQueue {
public:
    WriterQueue() = default;
    ~WriterQueue() { stop(); }
    WriterQueue(const WriterQueue&) = delete;
    WriterQueue& operator=(const WriterQueue&) = delete;

    // Open (truncate) `path`, write the header, start the writer thread.
    // ring_capacity_records must be a power of two.
    bool start(const std::string& path, size_t ring_capacity_records = 1u << 16);

    // Drain everything already pushed, sync, trim the file to its true size,
    // join the writer thread. Call from the producer thread AFTER its last push.
    void stop();

    // ----------------------- producer side (Thread C only) -----------------
    // One triangulated state from a validated track.
    inline void push(int64_t global_id, const State3D& s) noexcept {
        if (!ring_ || !ring_->reserve(1)) { count_drop(1); return; }
        raemot3d_file::Record& r = ring_->slot(0);
        fill_point(r, global_id, s);
        ring_->commit(1);
    }

    // Track just validated: OPEN record + the whole candidate buffer, published
    // atomically (either all of it reaches the ring or none of it).
    inline void push_track_start(int64_t global_id, double tg, int32_t a_track_id,
                                 int32_t b_track_id, const State3D* pts, size_t n) noexcept {
        const size_t total = n + 1;
        if (!ring_ || !ring_->reserve(total)) { count_drop(total); return; }

        raemot3d_file::Record& o = ring_->slot(0);
        o.type = raemot3d_file::REC_OPEN;
        o.global_id = static_cast<uint32_t>(global_id);
        o.tg = tg;
        o.payload.open = raemot3d_file::OpenPayload{};      // zero the reserved bytes
        o.payload.open.a_track_id = a_track_id;
        o.payload.open.b_track_id = b_track_id;

        for (size_t i = 0; i < n; ++i) fill_point(ring_->slot(i + 1), global_id, pts[i]);
        ring_->commit(total);
    }

    inline void push_close_marker(int64_t global_id, double tg) noexcept {
        if (!ring_ || !ring_->reserve(1)) { count_drop(1); return; }
        raemot3d_file::Record& c = ring_->slot(0);
        c.type = raemot3d_file::REC_CLOSE;
        c.global_id = static_cast<uint32_t>(global_id);
        c.tg = tg;
        c.payload.close = raemot3d_file::ClosePayload{};
        ring_->commit(1);
    }

    // ----------------------- stats (safe from any thread) ------------------
    uint64_t dropped_records() const { return dropped_.load(std::memory_order_relaxed); }
    uint64_t written_records() const { return written_.load(std::memory_order_relaxed); }
    bool     io_failed()       const { return io_failed_.load(std::memory_order_relaxed); }

private:
    static inline void fill_point(raemot3d_file::Record& r, int64_t id, const State3D& s) noexcept {
        r.type = raemot3d_file::REC_POINT;
        r.global_id = static_cast<uint32_t>(id);
        r.tg = s.tg;
        r.payload.point = raemot3d_file::PointPayload{s.x, s.y, s.z, s.vx, s.vy, s.vz};
    }
    inline void count_drop(size_t n) noexcept { dropped_.fetch_add(n, std::memory_order_relaxed); }

    // writer thread
    void run();
    bool write_bytes(const void* data, size_t len);

    std::unique_ptr<SpscRing<raemot3d_file::Record>> ring_;
    std::thread thread_;
    std::atomic<bool> running_{false};
    std::atomic<uint64_t> dropped_{0};
    std::atomic<uint64_t> written_{0};
    std::atomic<bool> io_failed_{false};

    // touched only by the writer thread (after start())
    int      fd_ = -1;
    uint64_t bytes_total_ = 0;      // bytes actually written (header + records)
    uint64_t allocated_ = 0;        // bytes preallocated so far
    bool     prealloc_ok_ = true;
    bool     dirty_ = false;
};